plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs9.github.io
baseurl: "/w24"

course: "CS 9"
qtr: "W24"
instructor: "Prof K" 
quarter: "Winter 2024"

# also used in _data/navigation.yml
piazza_url: https://piazza.com/class/lr6pnwwwf0a18a
gauchospace_url:
gradescope_url: https://www.gradescope.com/courses/694482

github_url: https://github.com/ucsb-cs9/w24
slides_url: https://drive.google.com/drive/folders/1hbJOKO7OPaPLbaFKxAzueFKKYDqlJqOz

start_week: 1 # 0 in the Fall, when we start qtr in the middle of a week (week 0)
start_date: 2024-01-07 00:00:00.00-7:00  # has to be a Sunday
num_weeks: 10 # 11 is needed in the Fall, when we start qtr in the middle of a week (week 0)
extra_exam_week: true

# ### https://registrar.sa.ucsb.edu/calendars/calendars-deadlines/academic-calendars
# ### https://registrar.sa.ucsb.edu/calendars/calendars-deadlines/registration-pass-dates
cal_dates: >                                                                    
  [                                                                            
    {"label":"W24 1st day of instruction", "date":"2023-01-08" },
    {"label":"Holiday: MLK Jr. Day",  "date":"2024-01-15" },
    {"label":"Holiday: Presidents' Day",  "date":"2024-02-19" },
    {"label":"W24 deadline to drop courses", "date":"2024-02-05" },
    {"label":"W24 CS 9 MIDTERM", "date":"2024-02-08" },
    {"label":"W24 CS 9 FINAL (4:00pm - 6:00pm)", "date":"2024-03-19" },
    {"label":"W24 instruction ends", "date":"2024-03-15" },
    {"label":"W24 qtr ends", "date":"2024-03-22" }
  ]

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
